name: Android Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup google-services.json for CI
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

    - name: Generate debug keystore for CI
      run: |
        keytool -genkey -v -keystore app/debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Release APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: RummyPulse ${{ github.ref_name }}
        body: |
          ## RummyPulse Android App - Release
          
          **Version:** ${{ github.ref_name }}
          **Commit:** ${{ github.sha }}
          **Date:** ${{ github.event.head_commit.timestamp }}
          
          ### Installation Instructions
          1. Download the APK file below
          2. Enable "Install from unknown sources" in your Android device settings
          3. Install the APK on your device
          
          ### Changes
          ${{ github.event.head_commit.message }}
        files: app/build/outputs/apk/release/app-release.apk
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
